#!/bin/sh
# Copyright (C) 2000-2017 Synology Inc. All rights reserved.

case $1 in
	start)
		/sbin/insmod $SYNOPKG_PKGDEST/aqc111/mii.ko
		/sbin/insmod $SYNOPKG_PKGDEST/aqc111/usbnet.ko
		/sbin/insmod $SYNOPKG_PKGDEST/aqc111/aqc111.ko
		exit 0
	;;
	stop)
		/sbin/rmmod $SYNOPKG_PKGDEST/aqc111/aqc111.ko
		/sbin/rmmod $SYNOPKG_PKGDEST/aqc111/usbnet.ko
		/sbin/rmmod $SYNOPKG_PKGDEST/aqc111/mii.ko
		exit 0
	;;
	status)
		/sbin/lsmod | grep aqc111 && exit 0 || exit 3
	;;
	killall)
        ;;
	log)
		exit 0
	;;
esac

